apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gateway-api-crds
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: platform
  source:
    repoURL: "https://github.com/necdetsanli/homelab.git"
    targetRevision: "main"
    path: vendor/gateway-api/v1.4.1
  destination:
    server: "https://kubernetes.default.svc"
    namespace: "kube-system"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
