apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gateway-config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: platform
  source:
    repoURL: "https://github.com/necdetsanli/homelab.git"
    targetRevision: "main"
    path: clusters/k8s-home-arpa/apps/infra/gateway-config
  destination:
    server: "https://kubernetes.default.svc"
    namespace: "gateway-system"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
