apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - application-cert-manager.yaml
  - application-metallb.yaml
  - application-metallb-config.yaml
  - application-cilium-bgp.yaml
  # - application-ingress-nginx.yaml   # Phase 3
  # - application-istio.yaml           # Phase 4
