apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - application-cert-manager.yaml
  - application-cert-manager-config.yaml
  - application-metallb.yaml
  - application-metallb-config.yaml
  - application-cilium-bgp.yaml
  - application-vso.yaml
  - application-vso-config.yaml
  - application-longhorn.yaml
  - application-gateway-api.yaml
  - application-gateway-config.yaml
  # - application-ingress-nginx.yaml   # Removed: HAProxy edge tier handles routing
  # - application-istio.yaml           # Future consideration
